url: https://fitnut.github.io
baseurl: 

# Site settings
title: Fitnut
email: fitnut@163.com
description: "Fitnut坚果健身，坚持健身，果然有效~"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people1:
- name: 沈易培
  pic: 1
  position: 用户体验设计

- name: 李心成
  pic: 2
  position: 软硬件集成

- name: 姚丹
  pic: 3
  position: 软件开发

people2:
- name: 赵瀚森
  pic: 4
  position: 硬件开发

- name: 曹广
  pic: 5
  position: 工业设计

- name: 曹宇哲
  pic: 6
  position: 品牌推广

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 北京市海淀区
  - line: 清华园1号

# Build settings
markdown: kramdown
permalink: pretty